-- AddForeignKey
ALTER TABLE "CHANGES" ADD CONSTRAINT "CHANGES_SPSO_id_fkey" FOREIGN KEY ("SPSO_id") REFERENCES "SPSO"("SPSO_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHANGES" ADD CONSTRAINT "CHANGES_SP_id_fkey" FOREIGN KEY ("SP_id") REFERENCES "SYSTEM_POLICY"("SP_id") ON DELETE RESTRICT ON UPDATE CASCADE;
